#生产环境配置
server:
  port: 8010
springdoc:
  api-docs:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  mail:
    host: smtp.163.com
    username: chalys2021@163.com
    password: QLWTZHQLHAGBQQZL
  rabbitmq:
    addresses: monitor-rabbitmq
    username: admin
    password: monitorrabbitmqadmin
    virtual-host: /
  influx:
    url: http://monitor-influxdb:8086/
    user: admin
    password: monitorinfluxdbadmin
  datasource:
    url: jdbc:mysql://monitor-mysql:3306/lite-monitor-db
    username: root
    password: monitormysqlroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 1000
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  data:
    redis:
      host: monitor-redis
      port: 6379
      database: 0